version: '3.8'

services:
  database:
    image: postgres:17
    container_name: tskmngr_database_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - tskmngr_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_CORS_URL: ${FRONTEND_CORS_URL}
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"

volumes:
  tskmngr_data: